export const LOAD_INVOICE_SUCCESS = 'LOAD_INVOICE_SUCCESS';
export const INACTIVE_INVOICE_DONE = "INACTIVE_INVOICE_DONE";
export const ACTIVE_INVOICE_DONE = "ACTIVE_INVOICE_DONE";
export const EDIT_INVOICE_DONE = "EDIT_INVOICE_DONE";