export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const INACTIVE_PRODUCT_DONE = "INACTIVE_PRODUCT_DONE";
export const ACTIVE_PRODUCT_DONE = "ACTIVE_PRODUCT_DONE";
export const EDIT_PRODUCT_DONE = "EDIT_PRODUCT_DONE";