export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const INACTIVE_USER_DONE = "INACTIVE_USER_DONE";
export const ACTIVE_USER_DONE = "ACTIVE_USER_DONE";
export const EDIT_USER_DONE = "EDIT_USER_DONE";